[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "HDD"
version = "0.1.0"
description = "A tools package"
authors = [{ name = "Metaer" }]
readme = ""
license = { text = "MIT" }
requires-python = ">=3.10"
